In [4]:
import numpy as np

In [5]:
mylist = [1, 2, 3]

In [6]:
type(mylist)

list

In [7]:
np.array(mylist)

array([1, 2, 3])

In [8]:
myarray = np.array(mylist)

In [9]:
type(myarray)

numpy.ndarray

In [10]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
len(np.linspace(0, 5, 21))

21

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(2, 4)

array([[0.57747157, 0.82178924, 0.03930951, 0.89382298],
       [0.21209309, 0.70066385, 0.50953707, 0.1521697 ]])

In [41]:
np.random.randn(2, 4)

array([[ 1.08388425,  0.49186884,  1.49503407, -1.17607063],
       [ 0.47978777,  1.50486556,  1.48161227, -1.27374326]])

In [54]:
np.random.randint(0, 101, (3, 4))

array([[32, 60, 42, 86],
       [40, 71, 80, 62],
       [54, 15, 94,  7]])

In [58]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [59]:
np.random.seed(43)
np.random.rand(4)

array([0.11505457, 0.60906654, 0.13339096, 0.24058962])

In [60]:
arr = np.arange(0, 25)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr.reshape((5, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
randArr = np.random.randint(0, 101, 10)

In [64]:
randArr

array([17, 59, 91, 66, 30, 87, 64, 35, 50, 75])

In [65]:
randArr.max()

91

In [66]:
randArr.min()

17

In [70]:
randArr.argmax()

2

In [69]:
randArr.argmin()

0

In [71]:
randArr.dtype

dtype('int32')

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
arr.shape

(25,)

In [74]:
arr = arr.reshape(5, 5)

In [75]:
arr.shape

(5, 5)

In [78]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])